apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: hello-world
spec:
  type: NodePort
  ports:
  - nodePort: 30001
    port: 8080
    protocol: TCP
  selector:
    app: hello-world
  
